apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bf7757uox-python-gitops
  description: This is GitOps manifest for bf7757uox-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bf7757uox-python
    janus-idp.io/tekton: bf7757uox-python 
    backstage.io/kubernetes-id: bf7757uox-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bf7757uox-python
