apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bf7757uox-python
  janus-idp.io/tekton: bf7757uox-python
  backstage.io/kubernetes-id: bf7757uox-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bf7757uox-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
